name: RunCode

on:
  issues:
    types: [opened]

jobs:
  move:

    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'step|')
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set env vars
      run: |
        echo ::set-env name=REPOSITORY::${{ github.repository }}
        echo ::set-env name=EVENT_ISSUE_NUMBER::${{ github.event.issue.number }}
        echo ::set-env name=EVENT_USER_LOGIN::${{ github.event.issue.user.login }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run code
      run: |
        python -c 'print("test, ")'
        echo a $EVENT_ISSUE_NUMBER
        echo b $REPOSITORY
        echo c ${{ github.event.issue.title }}
        echo d 'EVENT_USER_LOGIN'
